Tracker:AddLocations("locations/hard/holodrum.json")
Tracker:AddLocations("locations/hard/subrosia.json")
Tracker:AddLocations("locations/hard/dungeons.json")
Tracker:AddLocations("locations/normal/holodrum.json")
Tracker:AddLocations("locations/normal/subrosia.json")
Tracker:AddLocations("locations/normal/dungeons.json")
Tracker:AddLocations("locations/normal/gnarled_root_dungeon.json")
Tracker:AddLocations("locations/normal/snakes_remains.json")
Tracker:AddLocations("locations/normal/poison_moths_lair.json")
Tracker:AddLocations("locations/normal/dancing_dragon_dungeon.json")
Tracker:AddLocations("locations/normal/unicorns_cave.json")
Tracker:AddLocations("locations/normal/ancient_ruins.json")
Tracker:AddLocations("locations/normal/explorers_crypt.json")
Tracker:AddLocations("locations/normal/sword_and_shield_maze.json")

