Tracker:AddLocations("locations/holodrum.json")
Tracker:AddLocations("locations/subrosia.json")
Tracker:AddLocations("locations/dungeons.json")
Tracker:AddLocations("locations/gnarled_root_dungeon.json")
Tracker:AddLocations("locations/snakes_remains.json")
Tracker:AddLocations("locations/poison_moths_lair.json")
Tracker:AddLocations("locations/dancing_dragon_dungeon.json")
Tracker:AddLocations("locations/unicorns_cave.json")
Tracker:AddLocations("locations/ancient_ruins.json")
Tracker:AddLocations("locations/explorers_crypt.json")
Tracker:AddLocations("locations/sword_and_shield_maze.json")

